---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ckdirections/mydirections/

    # Turn on maintenance mode.
    #- /home/ckstaging/mydirections/php artisan down

    - /bin/cp -r *.* $DEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH

    # Turn off maintenance mode
    #- /home/ckstaging/mydirections/php artisan up
