---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ckstaging/mydirections/

    # Turn on maintenance mode
    - /usr/local/bin/php /home/ckstaging/mydirections/artisan down

    - /bin/cp -r *.* $DEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH

    # Turn off maintenance mode
    #- /home/ckstaging/mydirections/php artisan up
