---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ckstaging/mydirections/

    # Turn on maintenance mode
    - /usr/local/bin/php /home/ckstaging/mydirections/artisan down

    - /bin/cp -r *.* $DEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH

    # Run database migrations
    #- /usr/local/bin/php /home/ckstaging/mydirections/artisan migrate --force

    # Clear and cache config
    - /usr/local/bin/php /home/ckstaging/mydirections/artisan config:clear
    #- /usr/local/bin/php /home/ckstaging/mydirections/artisan config:cache

    # Clear caches
    - /usr/local/bin/php /home/ckstaging/mydirections/artisan cache:clear

    # Clear and cache views
    - /usr/local/bin/php /home/ckstaging/mydirections/artisan view:clear
    - /usr/local/bin/php /home/ckstaging/mydirections/artisan view:cache

    # Clear and cache routes
    - /usr/local/bin/php /home/ckstaging/mydirections/artisan route:clear
    - /usr/local/bin/php /home/ckstaging/mydirections/artisan route:cache

    # Turn off maintenance mode
    - /usr/local/bin/php /home/ckstaging/mydirections/artisan up
