<div id="activity-settings" class="tab-pane px-0 @if ($activeTab == "activity-settings") active @else fade @endif" wire:key="activity-settings-pane">
    <div class="row">
        <div class="col-xl-8">
            <div class="rounded p-4 form-outer">
                <div class="form-group">
                    {!! Form::label('title', 'Activity Title'); !!}
                    {!! Form::text('title', null, array('placeholder' => 'Title','class' => 'form-control', 'maxlength' => 255, 'wire:model.debounce.200ms' => 'title')) !!}
                    @error('title') <div class="text-danger error">{{ $message }}</div>@enderror
                </div>

                <div class="form-group">
                    {!! Form::label('slug', 'URL'); !!}
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon3">{{ $this->baseUrl }}</span>
                        </div>
                        {!! Form::text('slug', null, array('placeholder' => 'URL','class' => 'form-control', 'maxlength' => 255, 'id' => 'slug', 'wire:model.lazy' => 'slug')) !!}
                    </div>
                    <small class="mt-2 d-block">The URL shown is autogenerated based on the activity title. It is not recommended to edit this field unless there is specific requirement to do so.</small>
                    @error('slug') <div class="text-danger error">{{ $message }}</div>@enderror
                </div>
            </div>
        </div>
    </div>
</div>
